import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import useSessionCheck from "@/hooks/useSessionCheck";
import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const { session, status } = useSessionCheck();
  const [navbarOpen, setNavbarOpen] = useState(false);

  console.log(session?.user);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar navbarOpen={navbarOpen} setNavbarOpen={setNavbarOpen} />
      <div className="flex flex-col flex-1 ">
        <Navbar
          navbarOpen={navbarOpen}
          setNavbarOpen={setNavbarOpen}
          title={"Главная"}
        />
        <section className="flex-1 p-5 overflow-auto bg-gray-50">
          <h1>
            Signed in as{" "}
            {session?.user?.firstName + " " + session?.user?.lastName}
          </h1>
          <h1>
            Signed in as{" "}
            {session?.user?.firstName + " " + session?.user?.lastName}
          </h1>
          <h1>
            Signed in as{" "}
            {session?.user?.firstName + " " + session?.user?.lastName}
          </h1>
          <h1>
            Signed in as{" "}
            {session?.user?.firstName + " " + session?.user?.lastName}
          </h1>
          <h1>
            Signed in as{" "}
            {session?.user?.firstName + " " + session?.user?.lastName}
          </h1>
          <h1>
            Signed in as{" "}
            {session?.user?.firstName + " " + session?.user?.lastName}
          </h1>
          <h1>
            Signed in as{" "}
            {session?.user?.firstName + " " + session?.user?.lastName}
          </h1>
          <h1>
            Signed in as{" "}
            {session?.user?.firstName + " " + session?.user?.lastName}
          </h1>
          <h1>
            Signed in as{" "}
            {session?.user?.firstName + " " + session?.user?.lastName}
          </h1>
          <h1>
            Signed in as{" "}
            {session?.user?.firstName + " " + session?.user?.lastName}
          </h1>
          <h1>
            Signed in as{" "}
            {session?.user?.firstName + " " + session?.user?.lastName}
          </h1>
          <h1>
            Signed in as{" "}
            {session?.user?.firstName + " " + session?.user?.lastName}
          </h1>
          <h1>
            Signed in as{" "}
            {session?.user?.firstName + " " + session?.user?.lastName}
          </h1>
          <h1>
            Signed in as{" "}
            {session?.user?.firstName + " " + session?.user?.lastName}
          </h1>
          <h1>
            Signed in as{" "}
            {session?.user?.firstName + " " + session?.user?.lastName}
          </h1>
          <h1>
            Signed in as{" "}
            {session?.user?.firstName + " " + session?.user?.lastName}
          </h1>
          <h1>
            Signed in as{" "}
            {session?.user?.firstName + " " + session?.user?.lastName}
          </h1>
          <h1>
            Signed in as{" "}
            {session?.user?.firstName + " " + session?.user?.lastName}
          </h1>
          <h1>
            Signed in as{" "}
            {session?.user?.firstName + " " + session?.user?.lastName}
          </h1>
          <h1>
            Signed in as{" "}
            {session?.user?.firstName + " " + session?.user?.lastName}
          </h1>
          <h1>
            Signed in as{" "}
            {session?.user?.firstName + " " + session?.user?.lastName}
          </h1>
          <h1>
            Signed in as{" "}
            {session?.user?.firstName + " " + session?.user?.lastName}
          </h1>
          <h1>
            Signed in as{" "}
            {session?.user?.firstName + " " + session?.user?.lastName}
          </h1>
          <h1>
            Signed in as{" "}
            {session?.user?.firstName + " " + session?.user?.lastName}
          </h1>
          <h1>
            Signed in as{" "}
            {session?.user?.firstName + " " + session?.user?.lastName}
          </h1>
          <h1>
            Signed in as{" "}
            {session?.user?.firstName + " " + session?.user?.lastName}
          </h1>
        </section>
      </div>
    </>
  );
}
