import { useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  const { data: session, status } = useSession();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="layout">
        <h1>Signed in as {session.user.firstName + " " + session.user.lastName}</h1>
      </section>
    </>
  );
}
